name: Deploy Changed HTML Files to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Change to your region

      - name: Detect changed HTML files
        id: changed_files
        run: |
          echo "Detecting changed files..."

          # Check if this is the first commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "First commit — uploading all files"
            FILES=$(find . -type f -not -path "./.git/*" -not -path "./.github/*")
          else
            echo "Getting files changed in the last commit only"
            FILES=$(git diff --name-only HEAD^ HEAD || true)
          fi

          echo "FILES: $FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload changed HTML files to S3
        if: steps.changed_files.outputs.files != ''
        run: |
          echo "Uploading changed files..."
          echo "${{ steps.changed_files.outputs.files }}" | while IFS= read -r file; do
            filename=$(basename "$file")
            echo "Uploading $file as $filename"
            aws s3 cp "$file" "s3://sampleawshosting/$filename"
          done
      
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EZOYY1XIE9Y0U \
            --paths "/*"
